//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE_API.SMSApiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSApiService.Ismsapi")]
    public interface Ismsapi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetApiKey", ReplyAction="http://tempuri.org/Ismsapi/GetApiKeyResponse")]
        string GetApiKey(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetApiKey", ReplyAction="http://tempuri.org/Ismsapi/GetApiKeyResponse")]
        System.Threading.Tasks.Task<string> GetApiKeyAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetErrorCodes", ReplyAction="http://tempuri.org/Ismsapi/GetErrorCodesResponse")]
        string GetErrorCodes(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetErrorCodes", ReplyAction="http://tempuri.org/Ismsapi/GetErrorCodesResponse")]
        System.Threading.Tasks.Task<string> GetErrorCodesAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetSenderIds", ReplyAction="http://tempuri.org/Ismsapi/GetSenderIdsResponse")]
        string GetSenderIds(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetSenderIds", ReplyAction="http://tempuri.org/Ismsapi/GetSenderIdsResponse")]
        System.Threading.Tasks.Task<string> GetSenderIdsAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetMesgTypes", ReplyAction="http://tempuri.org/Ismsapi/GetMesgTypesResponse")]
        string GetMesgTypes(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetMesgTypes", ReplyAction="http://tempuri.org/Ismsapi/GetMesgTypesResponse")]
        System.Threading.Tasks.Task<string> GetMesgTypesAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetBalanceCredits", ReplyAction="http://tempuri.org/Ismsapi/GetBalanceCreditsResponse")]
        string GetBalanceCredits(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetBalanceCredits", ReplyAction="http://tempuri.org/Ismsapi/GetBalanceCreditsResponse")]
        System.Threading.Tasks.Task<string> GetBalanceCreditsAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetCreditsExpiryTime", ReplyAction="http://tempuri.org/Ismsapi/GetCreditsExpiryTimeResponse")]
        string GetCreditsExpiryTime(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetCreditsExpiryTime", ReplyAction="http://tempuri.org/Ismsapi/GetCreditsExpiryTimeResponse")]
        System.Threading.Tasks.Task<string> GetCreditsExpiryTimeAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetUserExpiryTime", ReplyAction="http://tempuri.org/Ismsapi/GetUserExpiryTimeResponse")]
        string GetUserExpiryTime(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetUserExpiryTime", ReplyAction="http://tempuri.org/Ismsapi/GetUserExpiryTimeResponse")]
        System.Threading.Tasks.Task<string> GetUserExpiryTimeAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/SendTextSMS", ReplyAction="http://tempuri.org/Ismsapi/SendTextSMSResponse")]
        string SendTextSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/SendTextSMS", ReplyAction="http://tempuri.org/Ismsapi/SendTextSMSResponse")]
        System.Threading.Tasks.Task<string> SendTextSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/CalTextSmsCount", ReplyAction="http://tempuri.org/Ismsapi/CalTextSmsCountResponse")]
        string CalTextSmsCount(string apikey, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/CalTextSmsCount", ReplyAction="http://tempuri.org/Ismsapi/CalTextSmsCountResponse")]
        System.Threading.Tasks.Task<string> CalTextSmsCountAsync(string apikey, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/PushTextSMS", ReplyAction="http://tempuri.org/Ismsapi/PushTextSMSResponse")]
        string PushTextSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule, int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/PushTextSMS", ReplyAction="http://tempuri.org/Ismsapi/PushTextSMSResponse")]
        System.Threading.Tasks.Task<string> PushTextSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule, int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetCampaignDetails", ReplyAction="http://tempuri.org/Ismsapi/GetCampaignDetailsResponse")]
        string GetCampaignDetails(string apikey, ulong campaignid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetCampaignDetails", ReplyAction="http://tempuri.org/Ismsapi/GetCampaignDetailsResponse")]
        System.Threading.Tasks.Task<string> GetCampaignDetailsAsync(string apikey, ulong campaignid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetUserAllowedPrefixes", ReplyAction="http://tempuri.org/Ismsapi/GetUserAllowedPrefixesResponse")]
        string GetUserAllowedPrefixes(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetUserAllowedPrefixes", ReplyAction="http://tempuri.org/Ismsapi/GetUserAllowedPrefixesResponse")]
        System.Threading.Tasks.Task<string> GetUserAllowedPrefixesAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/ScheduleSMS", ReplyAction="http://tempuri.org/Ismsapi/ScheduleSMSResponse")]
        string ScheduleSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/ScheduleSMS", ReplyAction="http://tempuri.org/Ismsapi/ScheduleSMSResponse")]
        System.Threading.Tasks.Task<string> ScheduleSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/SendPrioritytSMS", ReplyAction="http://tempuri.org/Ismsapi/SendPrioritytSMSResponse")]
        string SendPrioritytSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/SendPrioritytSMS", ReplyAction="http://tempuri.org/Ismsapi/SendPrioritytSMSResponse")]
        System.Threading.Tasks.Task<string> SendPrioritytSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetMessagesStatus", ReplyAction="http://tempuri.org/Ismsapi/GetMessagesStatusResponse")]
        string GetMessagesStatus(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ismsapi/GetMessagesStatus", ReplyAction="http://tempuri.org/Ismsapi/GetMessagesStatusResponse")]
        System.Threading.Tasks.Task<string> GetMessagesStatusAsync(string apikey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsmsapiChannel : CORE_API.SMSApiService.Ismsapi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsmsapiClient : System.ServiceModel.ClientBase<CORE_API.SMSApiService.Ismsapi>, CORE_API.SMSApiService.Ismsapi {
        
        public IsmsapiClient() {
        }
        
        public IsmsapiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsmsapiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsmsapiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsmsapiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetApiKey(string username, string password) {
            return base.Channel.GetApiKey(username, password);
        }
        
        public System.Threading.Tasks.Task<string> GetApiKeyAsync(string username, string password) {
            return base.Channel.GetApiKeyAsync(username, password);
        }
        
        public string GetErrorCodes(string apikey) {
            return base.Channel.GetErrorCodes(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetErrorCodesAsync(string apikey) {
            return base.Channel.GetErrorCodesAsync(apikey);
        }
        
        public string GetSenderIds(string apikey) {
            return base.Channel.GetSenderIds(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetSenderIdsAsync(string apikey) {
            return base.Channel.GetSenderIdsAsync(apikey);
        }
        
        public string GetMesgTypes(string apikey) {
            return base.Channel.GetMesgTypes(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetMesgTypesAsync(string apikey) {
            return base.Channel.GetMesgTypesAsync(apikey);
        }
        
        public string GetBalanceCredits(string apikey) {
            return base.Channel.GetBalanceCredits(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetBalanceCreditsAsync(string apikey) {
            return base.Channel.GetBalanceCreditsAsync(apikey);
        }
        
        public string GetCreditsExpiryTime(string apikey) {
            return base.Channel.GetCreditsExpiryTime(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetCreditsExpiryTimeAsync(string apikey) {
            return base.Channel.GetCreditsExpiryTimeAsync(apikey);
        }
        
        public string GetUserExpiryTime(string apikey) {
            return base.Channel.GetUserExpiryTime(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetUserExpiryTimeAsync(string apikey) {
            return base.Channel.GetUserExpiryTimeAsync(apikey);
        }
        
        public string SendTextSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr) {
            return base.Channel.SendTextSMS(apikey, msg, msgtype, sid, mobiles, dlr);
        }
        
        public System.Threading.Tasks.Task<string> SendTextSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr) {
            return base.Channel.SendTextSMSAsync(apikey, msg, msgtype, sid, mobiles, dlr);
        }
        
        public string CalTextSmsCount(string apikey, string msg) {
            return base.Channel.CalTextSmsCount(apikey, msg);
        }
        
        public System.Threading.Tasks.Task<string> CalTextSmsCountAsync(string apikey, string msg) {
            return base.Channel.CalTextSmsCountAsync(apikey, msg);
        }
        
        public string PushTextSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule, int priority) {
            return base.Channel.PushTextSMS(apikey, msg, msgtype, sid, mobiles, dlr, schedule, priority);
        }
        
        public System.Threading.Tasks.Task<string> PushTextSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule, int priority) {
            return base.Channel.PushTextSMSAsync(apikey, msg, msgtype, sid, mobiles, dlr, schedule, priority);
        }
        
        public string GetCampaignDetails(string apikey, ulong campaignid) {
            return base.Channel.GetCampaignDetails(apikey, campaignid);
        }
        
        public System.Threading.Tasks.Task<string> GetCampaignDetailsAsync(string apikey, ulong campaignid) {
            return base.Channel.GetCampaignDetailsAsync(apikey, campaignid);
        }
        
        public string GetUserAllowedPrefixes(string apikey) {
            return base.Channel.GetUserAllowedPrefixes(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetUserAllowedPrefixesAsync(string apikey) {
            return base.Channel.GetUserAllowedPrefixesAsync(apikey);
        }
        
        public string ScheduleSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule) {
            return base.Channel.ScheduleSMS(apikey, msg, msgtype, sid, mobiles, dlr, schedule);
        }
        
        public System.Threading.Tasks.Task<string> ScheduleSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, ulong schedule) {
            return base.Channel.ScheduleSMSAsync(apikey, msg, msgtype, sid, mobiles, dlr, schedule);
        }
        
        public string SendPrioritytSMS(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, int priority) {
            return base.Channel.SendPrioritytSMS(apikey, msg, msgtype, sid, mobiles, dlr, priority);
        }
        
        public System.Threading.Tasks.Task<string> SendPrioritytSMSAsync(string apikey, string msg, int msgtype, string sid, string mobiles, int dlr, int priority) {
            return base.Channel.SendPrioritytSMSAsync(apikey, msg, msgtype, sid, mobiles, dlr, priority);
        }
        
        public string GetMessagesStatus(string apikey) {
            return base.Channel.GetMessagesStatus(apikey);
        }
        
        public System.Threading.Tasks.Task<string> GetMessagesStatusAsync(string apikey) {
            return base.Channel.GetMessagesStatusAsync(apikey);
        }
    }
}
