#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE_MODELS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CoreDbEngine")]
	public partial class DbEngineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSRCC_APILogs_HI(SRCC_APILogs_HI instance);
    partial void UpdateSRCC_APILogs_HI(SRCC_APILogs_HI instance);
    partial void DeleteSRCC_APILogs_HI(SRCC_APILogs_HI instance);
    partial void InsertFNGL_Accounts_TR(FNGL_Accounts_TR instance);
    partial void UpdateFNGL_Accounts_TR(FNGL_Accounts_TR instance);
    partial void DeleteFNGL_Accounts_TR(FNGL_Accounts_TR instance);
    partial void InsertSRCC_CardDebit_Reversal(SRCC_CardDebit_Reversal instance);
    partial void UpdateSRCC_CardDebit_Reversal(SRCC_CardDebit_Reversal instance);
    partial void DeleteSRCC_CardDebit_Reversal(SRCC_CardDebit_Reversal instance);
    partial void InsertSRCC_CardDebitTrans_TR(SRCC_CardDebitTrans_TR instance);
    partial void UpdateSRCC_CardDebitTrans_TR(SRCC_CardDebitTrans_TR instance);
    partial void DeleteSRCC_CardDebitTrans_TR(SRCC_CardDebitTrans_TR instance);
    partial void InsertFNGL_RefundTransactionTracking(FNGL_RefundTransactionTracking instance);
    partial void UpdateFNGL_RefundTransactionTracking(FNGL_RefundTransactionTracking instance);
    partial void DeleteFNGL_RefundTransactionTracking(FNGL_RefundTransactionTracking instance);
    partial void InsertSRCC_CardActivation_TR(SRCC_CardActivation_TR instance);
    partial void UpdateSRCC_CardActivation_TR(SRCC_CardActivation_TR instance);
    partial void DeleteSRCC_CardActivation_TR(SRCC_CardActivation_TR instance);
    partial void InsertSRCC_UserLogin_ST(SRCC_UserLogin_ST instance);
    partial void UpdateSRCC_UserLogin_ST(SRCC_UserLogin_ST instance);
    partial void DeleteSRCC_UserLogin_ST(SRCC_UserLogin_ST instance);
    #endregion
		
		public DbEngineDataContext() : 
				base(global::CORE_MODELS.Properties.Settings.Default.CoreDbEngineConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbEngineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbEngineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbEngineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbEngineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SRCC_APILogs_HI> SRCC_APILogs_HIs
		{
			get
			{
				return this.GetTable<SRCC_APILogs_HI>();
			}
		}
		
		public System.Data.Linq.Table<FNGL_Accounts_TR> FNGL_Accounts_TRs
		{
			get
			{
				return this.GetTable<FNGL_Accounts_TR>();
			}
		}
		
		public System.Data.Linq.Table<SRCC_CardDebit_Reversal> SRCC_CardDebit_Reversals
		{
			get
			{
				return this.GetTable<SRCC_CardDebit_Reversal>();
			}
		}
		
		public System.Data.Linq.Table<SRCC_CardDebitTrans_TR> SRCC_CardDebitTrans_TRs
		{
			get
			{
				return this.GetTable<SRCC_CardDebitTrans_TR>();
			}
		}
		
		public System.Data.Linq.Table<FNGL_RefundTransactionTracking> FNGL_RefundTransactionTrackings
		{
			get
			{
				return this.GetTable<FNGL_RefundTransactionTracking>();
			}
		}
		
		public System.Data.Linq.Table<SRCC_CardActivation_TR> SRCC_CardActivation_TRs
		{
			get
			{
				return this.GetTable<SRCC_CardActivation_TR>();
			}
		}
		
		public System.Data.Linq.Table<SRCC_UserLogin_ST> SRCC_UserLogin_ST
		{
			get
			{
				return this.GetTable<SRCC_UserLogin_ST>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GetAPIIncrementalValue")]
		public ISingleResult<SP_GetAPIIncrementalValueResult> SP_GetAPIIncrementalValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="APIId", DbType="Int")] System.Nullable<int> aPIId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aPIId);
			return ((ISingleResult<SP_GetAPIIncrementalValueResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SRCC_APILogs_HI")]
	public partial class SRCC_APILogs_HI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _APILogId;
		
		private System.Nullable<int> _APIId;
		
		private System.Nullable<int> _KeyId;
		
		private string _Request;
		
		private System.Nullable<System.DateTime> _RequestOn;
		
		private string _Response;
		
		private System.Nullable<System.DateTime> _ResponseOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAPILogIdChanging(int value);
    partial void OnAPILogIdChanged();
    partial void OnAPIIdChanging(System.Nullable<int> value);
    partial void OnAPIIdChanged();
    partial void OnKeyIdChanging(System.Nullable<int> value);
    partial void OnKeyIdChanged();
    partial void OnRequestChanging(string value);
    partial void OnRequestChanged();
    partial void OnRequestOnChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestOnChanged();
    partial void OnResponseChanging(string value);
    partial void OnResponseChanged();
    partial void OnResponseOnChanging(System.Nullable<System.DateTime> value);
    partial void OnResponseOnChanged();
    #endregion
		
		public SRCC_APILogs_HI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APILogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int APILogId
		{
			get
			{
				return this._APILogId;
			}
			set
			{
				if ((this._APILogId != value))
				{
					this.OnAPILogIdChanging(value);
					this.SendPropertyChanging();
					this._APILogId = value;
					this.SendPropertyChanged("APILogId");
					this.OnAPILogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APIId", DbType="Int")]
		public System.Nullable<int> APIId
		{
			get
			{
				return this._APIId;
			}
			set
			{
				if ((this._APIId != value))
				{
					this.OnAPIIdChanging(value);
					this.SendPropertyChanging();
					this._APIId = value;
					this.SendPropertyChanged("APIId");
					this.OnAPIIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyId", DbType="Int")]
		public System.Nullable<int> KeyId
		{
			get
			{
				return this._KeyId;
			}
			set
			{
				if ((this._KeyId != value))
				{
					this.OnKeyIdChanging(value);
					this.SendPropertyChanging();
					this._KeyId = value;
					this.SendPropertyChanged("KeyId");
					this.OnKeyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Request", DbType="VarChar(MAX)")]
		public string Request
		{
			get
			{
				return this._Request;
			}
			set
			{
				if ((this._Request != value))
				{
					this.OnRequestChanging(value);
					this.SendPropertyChanging();
					this._Request = value;
					this.SendPropertyChanged("Request");
					this.OnRequestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> RequestOn
		{
			get
			{
				return this._RequestOn;
			}
			set
			{
				if ((this._RequestOn != value))
				{
					this.OnRequestOnChanging(value);
					this.SendPropertyChanging();
					this._RequestOn = value;
					this.SendPropertyChanged("RequestOn");
					this.OnRequestOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Response", DbType="VarChar(MAX)")]
		public string Response
		{
			get
			{
				return this._Response;
			}
			set
			{
				if ((this._Response != value))
				{
					this.OnResponseChanging(value);
					this.SendPropertyChanging();
					this._Response = value;
					this.SendPropertyChanged("Response");
					this.OnResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResponseOn
		{
			get
			{
				return this._ResponseOn;
			}
			set
			{
				if ((this._ResponseOn != value))
				{
					this.OnResponseOnChanging(value);
					this.SendPropertyChanging();
					this._ResponseOn = value;
					this.SendPropertyChanged("ResponseOn");
					this.OnResponseOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FNGL_Accounts_TR")]
	public partial class FNGL_Accounts_TR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AccountId;
		
		private System.Nullable<int> _AccountTypeId;
		
		private System.Nullable<int> _ProductCode;
		
		private System.Nullable<char> _Status;
		
		private System.Nullable<decimal> _Balance;
		
		private string _WalletId;
		
		private string _AccountName;
		
		private string _EstId;
		
		private string _CustomerId;
		
		private string _IBAN;
		
		private System.Nullable<System.DateTime> _CloseDate;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<System.DateTime> _ModifiedOn;
		
		private System.Nullable<bool> _InitialLoad;
		
		private decimal _InitialLoadAmount;
		
		private EntitySet<SRCC_CardDebitTrans_TR> _SRCC_CardDebitTrans_TRs;
		
		private EntitySet<SRCC_CardActivation_TR> _SRCC_CardActivation_TRs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIdChanging(int value);
    partial void OnAccountIdChanged();
    partial void OnAccountTypeIdChanging(System.Nullable<int> value);
    partial void OnAccountTypeIdChanged();
    partial void OnProductCodeChanging(System.Nullable<int> value);
    partial void OnProductCodeChanged();
    partial void OnStatusChanging(System.Nullable<char> value);
    partial void OnStatusChanged();
    partial void OnBalanceChanging(System.Nullable<decimal> value);
    partial void OnBalanceChanged();
    partial void OnWalletIdChanging(string value);
    partial void OnWalletIdChanged();
    partial void OnAccountNameChanging(string value);
    partial void OnAccountNameChanged();
    partial void OnEstIdChanging(string value);
    partial void OnEstIdChanged();
    partial void OnCustomerIdChanging(string value);
    partial void OnCustomerIdChanged();
    partial void OnIBANChanging(string value);
    partial void OnIBANChanged();
    partial void OnCloseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCloseDateChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnModifiedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedOnChanged();
    partial void OnInitialLoadChanging(System.Nullable<bool> value);
    partial void OnInitialLoadChanged();
    partial void OnInitialLoadAmountChanging(decimal value);
    partial void OnInitialLoadAmountChanged();
    #endregion
		
		public FNGL_Accounts_TR()
		{
			this._SRCC_CardDebitTrans_TRs = new EntitySet<SRCC_CardDebitTrans_TR>(new Action<SRCC_CardDebitTrans_TR>(this.attach_SRCC_CardDebitTrans_TRs), new Action<SRCC_CardDebitTrans_TR>(this.detach_SRCC_CardDebitTrans_TRs));
			this._SRCC_CardActivation_TRs = new EntitySet<SRCC_CardActivation_TR>(new Action<SRCC_CardActivation_TR>(this.attach_SRCC_CardActivation_TRs), new Action<SRCC_CardActivation_TR>(this.detach_SRCC_CardActivation_TRs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountTypeId", DbType="Int")]
		public System.Nullable<int> AccountTypeId
		{
			get
			{
				return this._AccountTypeId;
			}
			set
			{
				if ((this._AccountTypeId != value))
				{
					this.OnAccountTypeIdChanging(value);
					this.SendPropertyChanging();
					this._AccountTypeId = value;
					this.SendPropertyChanged("AccountTypeId");
					this.OnAccountTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
		public System.Nullable<char> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WalletId", DbType="VarChar(30)")]
		public string WalletId
		{
			get
			{
				return this._WalletId;
			}
			set
			{
				if ((this._WalletId != value))
				{
					this.OnWalletIdChanging(value);
					this.SendPropertyChanging();
					this._WalletId = value;
					this.SendPropertyChanged("WalletId");
					this.OnWalletIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(100)")]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this.OnAccountNameChanging(value);
					this.SendPropertyChanging();
					this._AccountName = value;
					this.SendPropertyChanged("AccountName");
					this.OnAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstId", DbType="VarChar(30)")]
		public string EstId
		{
			get
			{
				return this._EstId;
			}
			set
			{
				if ((this._EstId != value))
				{
					this.OnEstIdChanging(value);
					this.SendPropertyChanging();
					this._EstId = value;
					this.SendPropertyChanged("EstId");
					this.OnEstIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="VarChar(100)")]
		public string CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="VarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this.OnIBANChanging(value);
					this.SendPropertyChanging();
					this._IBAN = value;
					this.SendPropertyChanged("IBAN");
					this.OnIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CloseDate
		{
			get
			{
				return this._CloseDate;
			}
			set
			{
				if ((this._CloseDate != value))
				{
					this.OnCloseDateChanging(value);
					this.SendPropertyChanging();
					this._CloseDate = value;
					this.SendPropertyChanged("CloseDate");
					this.OnCloseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialLoad", DbType="Bit")]
		public System.Nullable<bool> InitialLoad
		{
			get
			{
				return this._InitialLoad;
			}
			set
			{
				if ((this._InitialLoad != value))
				{
					this.OnInitialLoadChanging(value);
					this.SendPropertyChanging();
					this._InitialLoad = value;
					this.SendPropertyChanged("InitialLoad");
					this.OnInitialLoadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialLoadAmount", DbType="Decimal(18,2) NOT NULL")]
		public decimal InitialLoadAmount
		{
			get
			{
				return this._InitialLoadAmount;
			}
			set
			{
				if ((this._InitialLoadAmount != value))
				{
					this.OnInitialLoadAmountChanging(value);
					this.SendPropertyChanging();
					this._InitialLoadAmount = value;
					this.SendPropertyChanged("InitialLoadAmount");
					this.OnInitialLoadAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FNGL_Accounts_TR_SRCC_CardDebitTrans_TR", Storage="_SRCC_CardDebitTrans_TRs", ThisKey="AccountId", OtherKey="AccountId")]
		public EntitySet<SRCC_CardDebitTrans_TR> SRCC_CardDebitTrans_TRs
		{
			get
			{
				return this._SRCC_CardDebitTrans_TRs;
			}
			set
			{
				this._SRCC_CardDebitTrans_TRs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FNGL_Accounts_TR_SRCC_CardActivation_TR", Storage="_SRCC_CardActivation_TRs", ThisKey="AccountId", OtherKey="AccountId")]
		public EntitySet<SRCC_CardActivation_TR> SRCC_CardActivation_TRs
		{
			get
			{
				return this._SRCC_CardActivation_TRs;
			}
			set
			{
				this._SRCC_CardActivation_TRs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SRCC_CardDebitTrans_TRs(SRCC_CardDebitTrans_TR entity)
		{
			this.SendPropertyChanging();
			entity.FNGL_Accounts_TR = this;
		}
		
		private void detach_SRCC_CardDebitTrans_TRs(SRCC_CardDebitTrans_TR entity)
		{
			this.SendPropertyChanging();
			entity.FNGL_Accounts_TR = null;
		}
		
		private void attach_SRCC_CardActivation_TRs(SRCC_CardActivation_TR entity)
		{
			this.SendPropertyChanging();
			entity.FNGL_Accounts_TR = this;
		}
		
		private void detach_SRCC_CardActivation_TRs(SRCC_CardActivation_TR entity)
		{
			this.SendPropertyChanging();
			entity.FNGL_Accounts_TR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SRCC_CardDebit_Reversal")]
	public partial class SRCC_CardDebit_Reversal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _DebitId;
		
		private System.Nullable<bool> _IsCredited;
		
		private System.Nullable<System.DateTime> _InitiatedDate;
		
		private System.Nullable<System.DateTime> _SettlementDate;
		
		private string _TransReference;
		
		private string _TransDescription;
		
		private System.Nullable<int> _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<int> _ModifiedBy;
		
		private System.Nullable<System.DateTime> _ModifiedOn;
		
		private string _ProofImagePath;
		
		private System.Nullable<decimal> _RefundAmount;
		
		private System.Nullable<System.DateTime> _DateofFailure;
		
		private System.Nullable<int> _DebitRefundStatusId;
		
		private System.Nullable<int> _RefundApprovalStatusId;
		
		private System.Nullable<int> _CreditTransactionId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDebitIdChanging(System.Nullable<int> value);
    partial void OnDebitIdChanged();
    partial void OnIsCreditedChanging(System.Nullable<bool> value);
    partial void OnIsCreditedChanged();
    partial void OnInitiatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInitiatedDateChanged();
    partial void OnSettlementDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSettlementDateChanged();
    partial void OnTransReferenceChanging(string value);
    partial void OnTransReferenceChanged();
    partial void OnTransDescriptionChanging(string value);
    partial void OnTransDescriptionChanged();
    partial void OnCreatedByChanging(System.Nullable<int> value);
    partial void OnCreatedByChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnModifiedByChanging(System.Nullable<int> value);
    partial void OnModifiedByChanged();
    partial void OnModifiedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedOnChanged();
    partial void OnProofImagePathChanging(string value);
    partial void OnProofImagePathChanged();
    partial void OnRefundAmountChanging(System.Nullable<decimal> value);
    partial void OnRefundAmountChanged();
    partial void OnDateofFailureChanging(System.Nullable<System.DateTime> value);
    partial void OnDateofFailureChanged();
    partial void OnDebitRefundStatusIdChanging(System.Nullable<int> value);
    partial void OnDebitRefundStatusIdChanged();
    partial void OnRefundApprovalStatusIdChanging(System.Nullable<int> value);
    partial void OnRefundApprovalStatusIdChanged();
    partial void OnCreditTransactionIdChanging(System.Nullable<int> value);
    partial void OnCreditTransactionIdChanged();
    #endregion
		
		public SRCC_CardDebit_Reversal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebitId", DbType="Int")]
		public System.Nullable<int> DebitId
		{
			get
			{
				return this._DebitId;
			}
			set
			{
				if ((this._DebitId != value))
				{
					this.OnDebitIdChanging(value);
					this.SendPropertyChanging();
					this._DebitId = value;
					this.SendPropertyChanged("DebitId");
					this.OnDebitIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCredited", DbType="Bit")]
		public System.Nullable<bool> IsCredited
		{
			get
			{
				return this._IsCredited;
			}
			set
			{
				if ((this._IsCredited != value))
				{
					this.OnIsCreditedChanging(value);
					this.SendPropertyChanging();
					this._IsCredited = value;
					this.SendPropertyChanged("IsCredited");
					this.OnIsCreditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitiatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> InitiatedDate
		{
			get
			{
				return this._InitiatedDate;
			}
			set
			{
				if ((this._InitiatedDate != value))
				{
					this.OnInitiatedDateChanging(value);
					this.SendPropertyChanging();
					this._InitiatedDate = value;
					this.SendPropertyChanged("InitiatedDate");
					this.OnInitiatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettlementDate", DbType="Date")]
		public System.Nullable<System.DateTime> SettlementDate
		{
			get
			{
				return this._SettlementDate;
			}
			set
			{
				if ((this._SettlementDate != value))
				{
					this.OnSettlementDateChanging(value);
					this.SendPropertyChanging();
					this._SettlementDate = value;
					this.SendPropertyChanged("SettlementDate");
					this.OnSettlementDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransReference", DbType="VarChar(50)")]
		public string TransReference
		{
			get
			{
				return this._TransReference;
			}
			set
			{
				if ((this._TransReference != value))
				{
					this.OnTransReferenceChanging(value);
					this.SendPropertyChanging();
					this._TransReference = value;
					this.SendPropertyChanged("TransReference");
					this.OnTransReferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDescription", DbType="VarChar(200)")]
		public string TransDescription
		{
			get
			{
				return this._TransDescription;
			}
			set
			{
				if ((this._TransDescription != value))
				{
					this.OnTransDescriptionChanging(value);
					this.SendPropertyChanging();
					this._TransDescription = value;
					this.SendPropertyChanged("TransDescription");
					this.OnTransDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="Int")]
		public System.Nullable<int> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="Int")]
		public System.Nullable<int> ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProofImagePath", DbType="NVarChar(200)")]
		public string ProofImagePath
		{
			get
			{
				return this._ProofImagePath;
			}
			set
			{
				if ((this._ProofImagePath != value))
				{
					this.OnProofImagePathChanging(value);
					this.SendPropertyChanging();
					this._ProofImagePath = value;
					this.SendPropertyChanged("ProofImagePath");
					this.OnProofImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RefundAmount
		{
			get
			{
				return this._RefundAmount;
			}
			set
			{
				if ((this._RefundAmount != value))
				{
					this.OnRefundAmountChanging(value);
					this.SendPropertyChanging();
					this._RefundAmount = value;
					this.SendPropertyChanged("RefundAmount");
					this.OnRefundAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateofFailure", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateofFailure
		{
			get
			{
				return this._DateofFailure;
			}
			set
			{
				if ((this._DateofFailure != value))
				{
					this.OnDateofFailureChanging(value);
					this.SendPropertyChanging();
					this._DateofFailure = value;
					this.SendPropertyChanged("DateofFailure");
					this.OnDateofFailureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebitRefundStatusId", DbType="Int")]
		public System.Nullable<int> DebitRefundStatusId
		{
			get
			{
				return this._DebitRefundStatusId;
			}
			set
			{
				if ((this._DebitRefundStatusId != value))
				{
					this.OnDebitRefundStatusIdChanging(value);
					this.SendPropertyChanging();
					this._DebitRefundStatusId = value;
					this.SendPropertyChanged("DebitRefundStatusId");
					this.OnDebitRefundStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundApprovalStatusId", DbType="Int")]
		public System.Nullable<int> RefundApprovalStatusId
		{
			get
			{
				return this._RefundApprovalStatusId;
			}
			set
			{
				if ((this._RefundApprovalStatusId != value))
				{
					this.OnRefundApprovalStatusIdChanging(value);
					this.SendPropertyChanging();
					this._RefundApprovalStatusId = value;
					this.SendPropertyChanged("RefundApprovalStatusId");
					this.OnRefundApprovalStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditTransactionId", DbType="Int")]
		public System.Nullable<int> CreditTransactionId
		{
			get
			{
				return this._CreditTransactionId;
			}
			set
			{
				if ((this._CreditTransactionId != value))
				{
					this.OnCreditTransactionIdChanging(value);
					this.SendPropertyChanging();
					this._CreditTransactionId = value;
					this.SendPropertyChanged("CreditTransactionId");
					this.OnCreditTransactionIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SRCC_CardDebitTrans_TR")]
	public partial class SRCC_CardDebitTrans_TR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DebitId;
		
		private System.Nullable<int> _TransId;
		
		private string _CardNo;
		
		private string _ExpiryDate;
		
		private string _TransCode;
		
		private string _DebitAmount;
		
		private string _AmountCurrency;
		
		private string _FeeAmount;
		
		private string _RequestInfo;
		
		private System.Nullable<bool> _IsRequested;
		
		private System.Nullable<System.DateTime> _RequestedOn;
		
		private System.Nullable<bool> _PaymentSuccess;
		
		private string _PaymentTransId;
		
		private string _PaymentDescription;
		
		private string _MsgId;
		
		private string _Title;
		
		private string _Mode;
		
		private string _Description;
		
		private System.Nullable<int> _AccountId;
		
		private System.Nullable<bool> _IsLedgerAdded;
		
		private EntitySet<FNGL_RefundTransactionTracking> _FNGL_RefundTransactionTrackings;
		
		private EntityRef<FNGL_Accounts_TR> _FNGL_Accounts_TR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDebitIdChanging(int value);
    partial void OnDebitIdChanged();
    partial void OnTransIdChanging(System.Nullable<int> value);
    partial void OnTransIdChanged();
    partial void OnCardNoChanging(string value);
    partial void OnCardNoChanged();
    partial void OnExpiryDateChanging(string value);
    partial void OnExpiryDateChanged();
    partial void OnTransCodeChanging(string value);
    partial void OnTransCodeChanged();
    partial void OnDebitAmountChanging(string value);
    partial void OnDebitAmountChanged();
    partial void OnAmountCurrencyChanging(string value);
    partial void OnAmountCurrencyChanged();
    partial void OnFeeAmountChanging(string value);
    partial void OnFeeAmountChanged();
    partial void OnRequestInfoChanging(string value);
    partial void OnRequestInfoChanged();
    partial void OnIsRequestedChanging(System.Nullable<bool> value);
    partial void OnIsRequestedChanged();
    partial void OnRequestedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestedOnChanged();
    partial void OnPaymentSuccessChanging(System.Nullable<bool> value);
    partial void OnPaymentSuccessChanged();
    partial void OnPaymentTransIdChanging(string value);
    partial void OnPaymentTransIdChanged();
    partial void OnPaymentDescriptionChanging(string value);
    partial void OnPaymentDescriptionChanged();
    partial void OnMsgIdChanging(string value);
    partial void OnMsgIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnModeChanging(string value);
    partial void OnModeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAccountIdChanging(System.Nullable<int> value);
    partial void OnAccountIdChanged();
    partial void OnIsLedgerAddedChanging(System.Nullable<bool> value);
    partial void OnIsLedgerAddedChanged();
    #endregion
		
		public SRCC_CardDebitTrans_TR()
		{
			this._FNGL_RefundTransactionTrackings = new EntitySet<FNGL_RefundTransactionTracking>(new Action<FNGL_RefundTransactionTracking>(this.attach_FNGL_RefundTransactionTrackings), new Action<FNGL_RefundTransactionTracking>(this.detach_FNGL_RefundTransactionTrackings));
			this._FNGL_Accounts_TR = default(EntityRef<FNGL_Accounts_TR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebitId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DebitId
		{
			get
			{
				return this._DebitId;
			}
			set
			{
				if ((this._DebitId != value))
				{
					this.OnDebitIdChanging(value);
					this.SendPropertyChanging();
					this._DebitId = value;
					this.SendPropertyChanged("DebitId");
					this.OnDebitIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransId", DbType="Int")]
		public System.Nullable<int> TransId
		{
			get
			{
				return this._TransId;
			}
			set
			{
				if ((this._TransId != value))
				{
					this.OnTransIdChanging(value);
					this.SendPropertyChanging();
					this._TransId = value;
					this.SendPropertyChanged("TransId");
					this.OnTransIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(19)")]
		public string CardNo
		{
			get
			{
				return this._CardNo;
			}
			set
			{
				if ((this._CardNo != value))
				{
					this.OnCardNoChanging(value);
					this.SendPropertyChanging();
					this._CardNo = value;
					this.SendPropertyChanged("CardNo");
					this.OnCardNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="VarChar(8)")]
		public string ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this.OnExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDate = value;
					this.SendPropertyChanged("ExpiryDate");
					this.OnExpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransCode", DbType="VarChar(4)")]
		public string TransCode
		{
			get
			{
				return this._TransCode;
			}
			set
			{
				if ((this._TransCode != value))
				{
					this.OnTransCodeChanging(value);
					this.SendPropertyChanging();
					this._TransCode = value;
					this.SendPropertyChanged("TransCode");
					this.OnTransCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebitAmount", DbType="VarChar(25)")]
		public string DebitAmount
		{
			get
			{
				return this._DebitAmount;
			}
			set
			{
				if ((this._DebitAmount != value))
				{
					this.OnDebitAmountChanging(value);
					this.SendPropertyChanging();
					this._DebitAmount = value;
					this.SendPropertyChanged("DebitAmount");
					this.OnDebitAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountCurrency", DbType="VarChar(3)")]
		public string AmountCurrency
		{
			get
			{
				return this._AmountCurrency;
			}
			set
			{
				if ((this._AmountCurrency != value))
				{
					this.OnAmountCurrencyChanging(value);
					this.SendPropertyChanging();
					this._AmountCurrency = value;
					this.SendPropertyChanged("AmountCurrency");
					this.OnAmountCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeAmount", DbType="VarChar(25)")]
		public string FeeAmount
		{
			get
			{
				return this._FeeAmount;
			}
			set
			{
				if ((this._FeeAmount != value))
				{
					this.OnFeeAmountChanging(value);
					this.SendPropertyChanging();
					this._FeeAmount = value;
					this.SendPropertyChanged("FeeAmount");
					this.OnFeeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestInfo", DbType="VarChar(10)")]
		public string RequestInfo
		{
			get
			{
				return this._RequestInfo;
			}
			set
			{
				if ((this._RequestInfo != value))
				{
					this.OnRequestInfoChanging(value);
					this.SendPropertyChanging();
					this._RequestInfo = value;
					this.SendPropertyChanged("RequestInfo");
					this.OnRequestInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequested", DbType="Bit")]
		public System.Nullable<bool> IsRequested
		{
			get
			{
				return this._IsRequested;
			}
			set
			{
				if ((this._IsRequested != value))
				{
					this.OnIsRequestedChanging(value);
					this.SendPropertyChanging();
					this._IsRequested = value;
					this.SendPropertyChanged("IsRequested");
					this.OnIsRequestedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> RequestedOn
		{
			get
			{
				return this._RequestedOn;
			}
			set
			{
				if ((this._RequestedOn != value))
				{
					this.OnRequestedOnChanging(value);
					this.SendPropertyChanging();
					this._RequestedOn = value;
					this.SendPropertyChanged("RequestedOn");
					this.OnRequestedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentSuccess", DbType="Bit")]
		public System.Nullable<bool> PaymentSuccess
		{
			get
			{
				return this._PaymentSuccess;
			}
			set
			{
				if ((this._PaymentSuccess != value))
				{
					this.OnPaymentSuccessChanging(value);
					this.SendPropertyChanging();
					this._PaymentSuccess = value;
					this.SendPropertyChanged("PaymentSuccess");
					this.OnPaymentSuccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTransId", DbType="VarChar(10)")]
		public string PaymentTransId
		{
			get
			{
				return this._PaymentTransId;
			}
			set
			{
				if ((this._PaymentTransId != value))
				{
					this.OnPaymentTransIdChanging(value);
					this.SendPropertyChanging();
					this._PaymentTransId = value;
					this.SendPropertyChanged("PaymentTransId");
					this.OnPaymentTransIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentDescription", DbType="VarChar(MAX)")]
		public string PaymentDescription
		{
			get
			{
				return this._PaymentDescription;
			}
			set
			{
				if ((this._PaymentDescription != value))
				{
					this.OnPaymentDescriptionChanging(value);
					this.SendPropertyChanging();
					this._PaymentDescription = value;
					this.SendPropertyChanged("PaymentDescription");
					this.OnPaymentDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgId", DbType="VarChar(20)")]
		public string MsgId
		{
			get
			{
				return this._MsgId;
			}
			set
			{
				if ((this._MsgId != value))
				{
					this.OnMsgIdChanging(value);
					this.SendPropertyChanging();
					this._MsgId = value;
					this.SendPropertyChanged("MsgId");
					this.OnMsgIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(100)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode", DbType="VarChar(100)")]
		public string Mode
		{
			get
			{
				return this._Mode;
			}
			set
			{
				if ((this._Mode != value))
				{
					this.OnModeChanging(value);
					this.SendPropertyChanging();
					this._Mode = value;
					this.SendPropertyChanged("Mode");
					this.OnModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int")]
		public System.Nullable<int> AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					if (this._FNGL_Accounts_TR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLedgerAdded", DbType="Bit")]
		public System.Nullable<bool> IsLedgerAdded
		{
			get
			{
				return this._IsLedgerAdded;
			}
			set
			{
				if ((this._IsLedgerAdded != value))
				{
					this.OnIsLedgerAddedChanging(value);
					this.SendPropertyChanging();
					this._IsLedgerAdded = value;
					this.SendPropertyChanged("IsLedgerAdded");
					this.OnIsLedgerAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SRCC_CardDebitTrans_TR_FNGL_RefundTransactionTracking", Storage="_FNGL_RefundTransactionTrackings", ThisKey="DebitId", OtherKey="DebitId")]
		public EntitySet<FNGL_RefundTransactionTracking> FNGL_RefundTransactionTrackings
		{
			get
			{
				return this._FNGL_RefundTransactionTrackings;
			}
			set
			{
				this._FNGL_RefundTransactionTrackings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FNGL_Accounts_TR_SRCC_CardDebitTrans_TR", Storage="_FNGL_Accounts_TR", ThisKey="AccountId", OtherKey="AccountId", IsForeignKey=true)]
		public FNGL_Accounts_TR FNGL_Accounts_TR
		{
			get
			{
				return this._FNGL_Accounts_TR.Entity;
			}
			set
			{
				FNGL_Accounts_TR previousValue = this._FNGL_Accounts_TR.Entity;
				if (((previousValue != value) 
							|| (this._FNGL_Accounts_TR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FNGL_Accounts_TR.Entity = null;
						previousValue.SRCC_CardDebitTrans_TRs.Remove(this);
					}
					this._FNGL_Accounts_TR.Entity = value;
					if ((value != null))
					{
						value.SRCC_CardDebitTrans_TRs.Add(this);
						this._AccountId = value.AccountId;
					}
					else
					{
						this._AccountId = default(Nullable<int>);
					}
					this.SendPropertyChanged("FNGL_Accounts_TR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FNGL_RefundTransactionTrackings(FNGL_RefundTransactionTracking entity)
		{
			this.SendPropertyChanging();
			entity.SRCC_CardDebitTrans_TR = this;
		}
		
		private void detach_FNGL_RefundTransactionTrackings(FNGL_RefundTransactionTracking entity)
		{
			this.SendPropertyChanging();
			entity.SRCC_CardDebitTrans_TR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FNGL_RefundTransactionTracking")]
	public partial class FNGL_RefundTransactionTracking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RefundtrackingId;
		
		private System.Nullable<int> _DebitId;
		
		private System.Nullable<decimal> _RefundAmount;
		
		private string _Description;
		
		private string _Comment;
		
		private System.Nullable<int> _RefundApprovalStatusId;
		
		private System.Nullable<System.DateTime> _Createdon;
		
		private System.Nullable<int> _Createdby;
		
		private EntityRef<SRCC_CardDebitTrans_TR> _SRCC_CardDebitTrans_TR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRefundtrackingIdChanging(int value);
    partial void OnRefundtrackingIdChanged();
    partial void OnDebitIdChanging(System.Nullable<int> value);
    partial void OnDebitIdChanged();
    partial void OnRefundAmountChanging(System.Nullable<decimal> value);
    partial void OnRefundAmountChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnRefundApprovalStatusIdChanging(System.Nullable<int> value);
    partial void OnRefundApprovalStatusIdChanged();
    partial void OnCreatedonChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedonChanged();
    partial void OnCreatedbyChanging(System.Nullable<int> value);
    partial void OnCreatedbyChanged();
    #endregion
		
		public FNGL_RefundTransactionTracking()
		{
			this._SRCC_CardDebitTrans_TR = default(EntityRef<SRCC_CardDebitTrans_TR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundtrackingId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RefundtrackingId
		{
			get
			{
				return this._RefundtrackingId;
			}
			set
			{
				if ((this._RefundtrackingId != value))
				{
					this.OnRefundtrackingIdChanging(value);
					this.SendPropertyChanging();
					this._RefundtrackingId = value;
					this.SendPropertyChanged("RefundtrackingId");
					this.OnRefundtrackingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebitId", DbType="Int")]
		public System.Nullable<int> DebitId
		{
			get
			{
				return this._DebitId;
			}
			set
			{
				if ((this._DebitId != value))
				{
					if (this._SRCC_CardDebitTrans_TR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDebitIdChanging(value);
					this.SendPropertyChanging();
					this._DebitId = value;
					this.SendPropertyChanged("DebitId");
					this.OnDebitIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RefundAmount
		{
			get
			{
				return this._RefundAmount;
			}
			set
			{
				if ((this._RefundAmount != value))
				{
					this.OnRefundAmountChanging(value);
					this.SendPropertyChanging();
					this._RefundAmount = value;
					this.SendPropertyChanged("RefundAmount");
					this.OnRefundAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NChar(40)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundApprovalStatusId", DbType="Int")]
		public System.Nullable<int> RefundApprovalStatusId
		{
			get
			{
				return this._RefundApprovalStatusId;
			}
			set
			{
				if ((this._RefundApprovalStatusId != value))
				{
					this.OnRefundApprovalStatusIdChanging(value);
					this.SendPropertyChanging();
					this._RefundApprovalStatusId = value;
					this.SendPropertyChanged("RefundApprovalStatusId");
					this.OnRefundApprovalStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdon", DbType="DateTime")]
		public System.Nullable<System.DateTime> Createdon
		{
			get
			{
				return this._Createdon;
			}
			set
			{
				if ((this._Createdon != value))
				{
					this.OnCreatedonChanging(value);
					this.SendPropertyChanging();
					this._Createdon = value;
					this.SendPropertyChanged("Createdon");
					this.OnCreatedonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdby", DbType="Int")]
		public System.Nullable<int> Createdby
		{
			get
			{
				return this._Createdby;
			}
			set
			{
				if ((this._Createdby != value))
				{
					this.OnCreatedbyChanging(value);
					this.SendPropertyChanging();
					this._Createdby = value;
					this.SendPropertyChanged("Createdby");
					this.OnCreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SRCC_CardDebitTrans_TR_FNGL_RefundTransactionTracking", Storage="_SRCC_CardDebitTrans_TR", ThisKey="DebitId", OtherKey="DebitId", IsForeignKey=true)]
		public SRCC_CardDebitTrans_TR SRCC_CardDebitTrans_TR
		{
			get
			{
				return this._SRCC_CardDebitTrans_TR.Entity;
			}
			set
			{
				SRCC_CardDebitTrans_TR previousValue = this._SRCC_CardDebitTrans_TR.Entity;
				if (((previousValue != value) 
							|| (this._SRCC_CardDebitTrans_TR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SRCC_CardDebitTrans_TR.Entity = null;
						previousValue.FNGL_RefundTransactionTrackings.Remove(this);
					}
					this._SRCC_CardDebitTrans_TR.Entity = value;
					if ((value != null))
					{
						value.FNGL_RefundTransactionTrackings.Add(this);
						this._DebitId = value.DebitId;
					}
					else
					{
						this._DebitId = default(Nullable<int>);
					}
					this.SendPropertyChanged("SRCC_CardDebitTrans_TR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SRCC_CardActivation_TR")]
	public partial class SRCC_CardActivation_TR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ActivationId;
		
		private System.Nullable<int> _ActionId;
		
		private string _CardNo;
		
		private string _Pin;
		
		private string _RequestType;
		
		private string _CardType;
		
		private string _FIID;
		
		private System.Nullable<bool> _IsRequested;
		
		private System.Nullable<System.DateTime> _RequestedOn;
		
		private System.Nullable<int> _AccountId;
		
		private string _NIStatus;
		
		private string _NIErrorCode;
		
		private string _NIDescription;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<int> _CardId;
		
		private EntityRef<FNGL_Accounts_TR> _FNGL_Accounts_TR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActivationIdChanging(int value);
    partial void OnActivationIdChanged();
    partial void OnActionIdChanging(System.Nullable<int> value);
    partial void OnActionIdChanged();
    partial void OnCardNoChanging(string value);
    partial void OnCardNoChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnRequestTypeChanging(string value);
    partial void OnRequestTypeChanged();
    partial void OnCardTypeChanging(string value);
    partial void OnCardTypeChanged();
    partial void OnFIIDChanging(string value);
    partial void OnFIIDChanged();
    partial void OnIsRequestedChanging(System.Nullable<bool> value);
    partial void OnIsRequestedChanged();
    partial void OnRequestedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestedOnChanged();
    partial void OnAccountIdChanging(System.Nullable<int> value);
    partial void OnAccountIdChanged();
    partial void OnNIStatusChanging(string value);
    partial void OnNIStatusChanged();
    partial void OnNIErrorCodeChanging(string value);
    partial void OnNIErrorCodeChanged();
    partial void OnNIDescriptionChanging(string value);
    partial void OnNIDescriptionChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnCardIdChanging(System.Nullable<int> value);
    partial void OnCardIdChanged();
    #endregion
		
		public SRCC_CardActivation_TR()
		{
			this._FNGL_Accounts_TR = default(EntityRef<FNGL_Accounts_TR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivationId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ActivationId
		{
			get
			{
				return this._ActivationId;
			}
			set
			{
				if ((this._ActivationId != value))
				{
					this.OnActivationIdChanging(value);
					this.SendPropertyChanging();
					this._ActivationId = value;
					this.SendPropertyChanged("ActivationId");
					this.OnActivationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionId", DbType="Int")]
		public System.Nullable<int> ActionId
		{
			get
			{
				return this._ActionId;
			}
			set
			{
				if ((this._ActionId != value))
				{
					this.OnActionIdChanging(value);
					this.SendPropertyChanging();
					this._ActionId = value;
					this.SendPropertyChanged("ActionId");
					this.OnActionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(19)")]
		public string CardNo
		{
			get
			{
				return this._CardNo;
			}
			set
			{
				if ((this._CardNo != value))
				{
					this.OnCardNoChanging(value);
					this.SendPropertyChanging();
					this._CardNo = value;
					this.SendPropertyChanged("CardNo");
					this.OnCardNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="VarChar(25)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestType", DbType="VarChar(2)")]
		public string RequestType
		{
			get
			{
				return this._RequestType;
			}
			set
			{
				if ((this._RequestType != value))
				{
					this.OnRequestTypeChanging(value);
					this.SendPropertyChanging();
					this._RequestType = value;
					this.SendPropertyChanged("RequestType");
					this.OnRequestTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardType", DbType="VarChar(10)")]
		public string CardType
		{
			get
			{
				return this._CardType;
			}
			set
			{
				if ((this._CardType != value))
				{
					this.OnCardTypeChanging(value);
					this.SendPropertyChanging();
					this._CardType = value;
					this.SendPropertyChanged("CardType");
					this.OnCardTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIID", DbType="VarChar(10)")]
		public string FIID
		{
			get
			{
				return this._FIID;
			}
			set
			{
				if ((this._FIID != value))
				{
					this.OnFIIDChanging(value);
					this.SendPropertyChanging();
					this._FIID = value;
					this.SendPropertyChanged("FIID");
					this.OnFIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequested", DbType="Bit")]
		public System.Nullable<bool> IsRequested
		{
			get
			{
				return this._IsRequested;
			}
			set
			{
				if ((this._IsRequested != value))
				{
					this.OnIsRequestedChanging(value);
					this.SendPropertyChanging();
					this._IsRequested = value;
					this.SendPropertyChanged("IsRequested");
					this.OnIsRequestedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> RequestedOn
		{
			get
			{
				return this._RequestedOn;
			}
			set
			{
				if ((this._RequestedOn != value))
				{
					this.OnRequestedOnChanging(value);
					this.SendPropertyChanging();
					this._RequestedOn = value;
					this.SendPropertyChanged("RequestedOn");
					this.OnRequestedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int")]
		public System.Nullable<int> AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					if (this._FNGL_Accounts_TR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIStatus", DbType="NVarChar(200)")]
		public string NIStatus
		{
			get
			{
				return this._NIStatus;
			}
			set
			{
				if ((this._NIStatus != value))
				{
					this.OnNIStatusChanging(value);
					this.SendPropertyChanging();
					this._NIStatus = value;
					this.SendPropertyChanged("NIStatus");
					this.OnNIStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIErrorCode", DbType="NVarChar(200)")]
		public string NIErrorCode
		{
			get
			{
				return this._NIErrorCode;
			}
			set
			{
				if ((this._NIErrorCode != value))
				{
					this.OnNIErrorCodeChanging(value);
					this.SendPropertyChanging();
					this._NIErrorCode = value;
					this.SendPropertyChanged("NIErrorCode");
					this.OnNIErrorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIDescription", DbType="NVarChar(200)")]
		public string NIDescription
		{
			get
			{
				return this._NIDescription;
			}
			set
			{
				if ((this._NIDescription != value))
				{
					this.OnNIDescriptionChanging(value);
					this.SendPropertyChanging();
					this._NIDescription = value;
					this.SendPropertyChanged("NIDescription");
					this.OnNIDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardId", DbType="Int")]
		public System.Nullable<int> CardId
		{
			get
			{
				return this._CardId;
			}
			set
			{
				if ((this._CardId != value))
				{
					this.OnCardIdChanging(value);
					this.SendPropertyChanging();
					this._CardId = value;
					this.SendPropertyChanged("CardId");
					this.OnCardIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FNGL_Accounts_TR_SRCC_CardActivation_TR", Storage="_FNGL_Accounts_TR", ThisKey="AccountId", OtherKey="AccountId", IsForeignKey=true)]
		public FNGL_Accounts_TR FNGL_Accounts_TR
		{
			get
			{
				return this._FNGL_Accounts_TR.Entity;
			}
			set
			{
				FNGL_Accounts_TR previousValue = this._FNGL_Accounts_TR.Entity;
				if (((previousValue != value) 
							|| (this._FNGL_Accounts_TR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FNGL_Accounts_TR.Entity = null;
						previousValue.SRCC_CardActivation_TRs.Remove(this);
					}
					this._FNGL_Accounts_TR.Entity = value;
					if ((value != null))
					{
						value.SRCC_CardActivation_TRs.Add(this);
						this._AccountId = value.AccountId;
					}
					else
					{
						this._AccountId = default(Nullable<int>);
					}
					this.SendPropertyChanged("FNGL_Accounts_TR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	

	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SRCC_UserLogin_ST")]
	public partial class SRCC_UserLogin_ST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _UserName;
		
		private System.Nullable<char> _LoginType;
		
		private string _Password;
		
		private System.Nullable<int> _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private string _EmiratesId;
		
		private string _MobileNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLoginTypeChanging(System.Nullable<char> value);
    partial void OnLoginTypeChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCreatedByChanging(System.Nullable<int> value);
    partial void OnCreatedByChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnEmiratesIdChanging(string value);
    partial void OnEmiratesIdChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    #endregion
		
		public SRCC_UserLogin_ST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginType", DbType="Char(1)")]
		public System.Nullable<char> LoginType
		{
			get
			{
				return this._LoginType;
			}
			set
			{
				if ((this._LoginType != value))
				{
					this.OnLoginTypeChanging(value);
					this.SendPropertyChanging();
					this._LoginType = value;
					this.SendPropertyChanged("LoginType");
					this.OnLoginTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="Int")]
		public System.Nullable<int> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmiratesId", DbType="VarChar(50)")]
		public string EmiratesId
		{
			get
			{
				return this._EmiratesId;
			}
			set
			{
				if ((this._EmiratesId != value))
				{
					this.OnEmiratesIdChanging(value);
					this.SendPropertyChanging();
					this._EmiratesId = value;
					this.SendPropertyChanged("EmiratesId");
					this.OnEmiratesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="VarChar(40)")]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_GetAPIIncrementalValueResult
	{
		
		private System.Nullable<int> _IncrementalValue;
		
		public SP_GetAPIIncrementalValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncrementalValue", DbType="Int")]
		public System.Nullable<int> IncrementalValue
		{
			get
			{
				return this._IncrementalValue;
			}
			set
			{
				if ((this._IncrementalValue != value))
				{
					this._IncrementalValue = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
